spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: gulimall:8848
    alicloud:
      access-key: LTAI4G7zcnvhh9VM4yw1ikNF
      secret-key: OKEXnk4G2Fegr0oZLb7rkuquhCkyVq
      oss:
        endpoint: gulimall-bue.oss-cn-hangzhou.aliyuncs.com
        bucketname: gulimall-bue
server:
  port: 30000