spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: gulimall:8848
    alicloud:
      access-key: xxxxx
      secret-key: xxxxx
      oss:
        endpoint: gulimall-bue.oss-cn-hangzhou.aliyuncs.com
        bucketname: gulimall-bue
server:
  port: 30000