server:
  port: 11000
spring:
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: gulimall:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gulimall:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
mybatis-plus:
  mapper-locations: /mapper/**/*.xml
